[cimforge_custom]
EXTRACT-src_ip = (?<src_ip>\d+\.\d+\.\d+\.\d+)
EXTRACT-status = (?<status>\d{3})
EXTRACT-user = (?<user>\w+)
FIELDALIAS-src = src_ip as src
FIELDALIAS-dest = status as dest
EVAL-action = case(status>=200 AND status<300, "success", status>=400, "failure")
